const { jsPDF } = window.jspdf;


let imagen0 = document.getElementById("pdf0");
let imagen1 = document.getElementById("pdf1");
let boton = document.getElementById("pdfbtncrear");



boton.addEventListener("click", function (){
//document.addEventListener('DOMContentLoaded', function() {

    imagen0.hidden = false;

    let img1 = "";
    let img2 = "";

    html2canvas(imagen0).then((canvas0) => {
        let imgenBase64 = canvas0.toDataURL('image/jpeg', 1.0);
        //console.log(imgenBase64);
        img1 = imgenBase64;
        //console.log(img1);

    }).then(() => { html2canvas(imagen1).then((canvas1) => {
            let imgenBase641 = canvas1.toDataURL('image/jpeg', 1.0);
            //console.log(imgenBase641);
            img2 = imgenBase641;
            //console.log(img2);
            let doc = new jsPDF();
            doc.addImage(img1, 'JPEG', 15, 20, 200, 250);
            doc.addPage();
            doc.addImage(img2, 'JPEG', 15, 20, 200, 250);

            doc.save("prueba.pdf");
            window.location = "index.html"
        })});
    
    
   
   // html2canvas(imagen1).then((canvas1) => {
    //    let imgenBase641 = canvas1.toDataURL('image/png');
     //   console.log(imgenBase641);
      //  img2 = imgenBase641;
  //  });



   
    

});
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/*
function createPDFObject() {
    html2canvas(document.getElementById("main"), {
     onrendered:function(canvas) {
  
    var contentWidth = canvas.width;
    var contentHeight = canvas.height;
  
    //One page pdf shows the height of canvas generated by html page;
    var pageHeight = contentWidth / 592.28 * 841.89;
    //html page height without pdf generation
    var leftHeight = contentHeight;
    //Page offset
    var position = 0;
    //a4 paper size [595.28841.89], width and height of image in pdf of canvas generated by html page
    var imgWidth = 595.28; 
    var imgHeight = 592.28/contentWidth * contentHeight;
  
    //Return picture dataURL, parameters: picture format and sharpness (0-1)
    var pageData = canvas.toDataURL('image/jpeg', 1.0);
  
    //Direction is vertical by default, dimension ponits, format A4 [595.28841.89]
    var pdf = new jsPDF('', 'pt', 'a4');
    
    //There are two heights to distinguish, one is the actual height of the html page, and the height of the generated pdf page (841.89)
    //When the content does not exceed the display range of one page of pdf, paging is not required
    if (leftHeight < pageHeight) {
        pdf.addImage(pageData, 'JPEG', 0, 0, imgWidth, imgHeight );
    } else {
        while(leftHeight > 0) {
            pdf.addImage(pageData, 'JPEG', 0, position, imgWidth, imgHeight)
            leftHeight -= pageHeight;
            position -= 841.89;
            //Avoid adding blank pages
            if(leftHeight > 0) {
              pdf.addPage();
            }
        }
    }
     pdf.save('stone.pdf');
  
    }
   });


   

//crearPdf();

/*
//boton.addEventListener("click", function (){
    document.addEventListener('DOMContentLoaded', function() {

        imagen0.hidden = false;
    
        let img1 = "";
        let img2 = "";
    
        html2canvas(imagen0).then((canvas0) => {
            let imgenBase64 = canvas0.toDataURL('image/png');
            //console.log(imgenBase64);
            img1 = imgenBase64;
            //console.log(img1);
    
        }).then(() => { html2canvas(imagen1).then((canvas1) => {
                let imgenBase641 = canvas1.toDataURL('image/png');
                //console.log(imgenBase641);
                img2 = imgenBase641;
                //console.log(img2);
                var contentWidth = canvas0.width;
                var contentHeight = canvas0.height;
              
                //One page pdf shows the height of canvas generated by html page;
                var pageHeight = contentWidth / 592.28 * 841.89;
                //html page height without pdf generation
                var leftHeight = contentHeight;
                //Page offset
                var position = 0;
                //a4 paper size [595.28841.89], width and height of image in pdf of canvas generated by html page
                var imgWidth = 595.28; 
                var imgHeight = 592.28/contentWidth * contentHeight;
              
                //Return picture dataURL, parameters: picture format and sharpness (0-1)
                var pageData = canvas.toDataURL('image/jpeg', 1.0);
                let doc = new jsPDF();
                doc.addImage(img1, 'JPEG', 15, 40, 90, 90);
                doc.addPage();
                doc.addImage(img2, 'JPEG', 15, 40, 90, 90);
    
                doc.save("prueba.pdf");
                window.location = "index.html"
            })});
        
        
       
       // html2canvas(imagen1).then((canvas1) => {
        //    let imgenBase641 = canvas1.toDataURL('image/png');
         //   console.log(imgenBase641);
          //  img2 = imgenBase641;
      //  });
    
    
    
       
        
    
    });

    */